ASK WHERE {
	<http://www.blogger.com/profile/1109404> <http://xmlns.com/foaf/0.1/img> <http://localhost:8888/tests/xhtml1/photo1.jpg> .
	<http://localhost:8888/tests/xhtml1/photo1.jpg> <http://purl.org/dc/elements/1.1/creator> <http://www.blogger.com/profile/1109404> .
}


 
 
