ASK WHERE {
	<http://localhost:8888/tests/xhtml1/0055.xhtml> <http://purl.org/dc/elements/1.1/creator> <http://www-sop.inria.fr/acacia/fabien/> .
	<http://localhost:8888/tests/xhtml1/0055.xhtml> <http://purl.org/dc/elements/1.1/publisher> <http://www-sop.inria.fr/acacia/fabien/> .
}
