ASK WHERE {
    <http://www.example.org/#somebody> <http://xmlns.com/foaf/0.1/knows> <_:1> .
	<_:1>	<http://xmlns.com/foaf/0.1/knows> <http://www.ivan-herman.org/Ivan_Herman> .
	<_:1>	<http://xmlns.com/foaf/0.1/knows> <http://www.w3.org/People/Berners-Lee/card#i> .
	<_:1>	<http://xmlns.com/foaf/0.1/knows> <http://danbri.org/foaf.rdf#danbri> .
}
