ASK WHERE {
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#alternate> <http://example.org/alternate> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#appendix> <http://example.org/appendix> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#bookmark> <http://example.org/bookmark> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#cite> <http://example.org/cite> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#chapter> <http://example.org/chapter> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#contents> <http://example.org/contents> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#copyright> <http://example.org/copyright> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#glossary> <http://example.org/glossary> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#help> <http://example.org/help> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#icon> <http://example.org/icon> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#index> <http://example.org/index> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#meta> <http://example.org/meta> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#next> <http://example.org/next> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#p3pv1> <http://example.org/p3pv1> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#prev> <http://example.org/prev> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#role> <http://example.org/role> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#section> <http://example.org/section> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#subsection> <http://example.org/subsection> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#start> <http://example.org/start> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#license> <http://example.org/license> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#up> <http://example.org/up> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#first> <http://example.org/first> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#last> <http://example.org/last> .
<http://localhost:8888/tests/xhtml1/0087.xhtml> <http://www.w3.org/1999/xhtml/vocab#stylesheet> <http://example.org/stylesheet> .
}
