PREFIX xhv: <http://www.w3.org/1999/xhtml/vocab#>
PREFIX cc: <http://creativecommons.org/ns#>
PREFIX rdfatest: <http://rdfa.info/vocabs/rdfa-test#>
ASK WHERE {
  <http://localhost:8888/tests/xhtml1/0114.xhtml> xhv:index <http://localhost:8888/tests/#> .
  <http://localhost:8888/tests/xhtml1/0114.xhtml> xhv:next <http://localhost:8888/tests/xhtml1/0115.xhtml> .
  <http://localhost:8888/tests/xhtml1/0114.xhtml> xhv:up <http://localhost:8888/tests/xhtml1/> .
  <http://localhost:8888/tests/xhtml1/0114.xhtml> cc:attributionURL <http://localhost:8888/> .
  <http://localhost:8888/tests/xhtml1/0114.xhtml> rdfatest:cornerCase1 <http://localhost:8888/tests/xhtml1/> .
  <http://localhost:8888/tests/xhtml1/0114.xhtml> rdfatest:cornerCase3 <http://localhost:8888/tests/xhtml1/...> .
  <http://localhost:8888/tests/xhtml1/0114.xhtml> rdfatest:cornerCase4 <http://localhost:8888/tests/xhtml1/0114.xhtml?foo=bar../baz> .
  <http://localhost:8888/tests/xhtml1/0114.xhtml> rdfatest:cornerCase5 <http://localhost:8888/.../.htaccess> .
}
