ASK WHERE {
<http://localhost:8888/tests/xml/0115.xml> <http://www.example.com/entity1> ">" .
<http://localhost:8888/tests/xml/0115.xml> <http://www.example.com/entity2> "Ben & Co." .
<http://localhost:8888/tests/xml/0115.xml> <http://www.example.com/entity3> "@" .
<http://localhost:8888/tests/xml/0115.xml> <http://www.example.com/entity4> "@" .
}
