ASK WHERE {
	<http://localhost:8888/tests/html5/0015.html> <http://purl.org/dc/elements/1.1/creator> "Fyodor Dostoevsky" .
	<http://localhost:8888/tests/html5/0015.html> <http://purl.org/dc/elements/1.1/source> <urn:isbn:0140449132> .
}
