PREFIX xhv: <http://www.w3.org/1999/xhtml/vocab#>
PREFIX cc: <http://creativecommons.org/ns#>
PREFIX rdfatest: <http://rdfa.info/vocabs/rdfa-test#>
ASK WHERE {
  <http://localhost:8888/tests/html5/0114.html> xhv:index <http://rdfa.info/test-suite/#> .
  <http://localhost:8888/tests/html5/0114.html> xhv:next <http://localhost:8888/tests/html5/0115.html> .
  <http://localhost:8888/tests/html5/0114.html> xhv:up <http://localhost:8888/tests/html5/> .
  <http://localhost:8888/tests/html5/0114.html> cc:attributionURL <http://rdfa.info/> .
  <http://localhost:8888/tests/html5/0114.html> rdfatest:cornerCase1 <http://localhost:8888/tests/html5/> .
  <http://localhost:8888/tests/html5/0114.html> rdfatest:cornerCase3 <http://localhost:8888/tests/html5/...> .
  <http://localhost:8888/tests/html5/0114.html> rdfatest:cornerCase4 <http://localhost:8888/tests/html5/0114.html?foo=bar../baz> .
  <http://localhost:8888/tests/html5/0114.html> rdfatest:cornerCase5 <http://rdfa.info/test-suite/test-cases/.../.htaccess> .
}
