BASE <http://localhost:8888/tests/html5/0227.html>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
ASK WHERE {
  <http://localhost:8888/tests/html5/0227.html> rdf:value <_:3> .
  <_:3> rdf:first "Foo" .
  <_:3> rdf:next rdf:nil .
  <http://localhost:8888/tests/html5/0227.html> rdf:inlist <http://localhost:8888/tests/html5/res> .
  <http://localhost:8888/tests/html5/res> rdf:value <_:2> .
  <_:2> rdf:first "Bar" .
  <_:2> rdf:next rdf:nil .
}
