PREFIX rdfatest: <http://rdfa.info/vocabs/rdfa-test#>
ASK WHERE {
  <http://localhost:8888/tests/html5/0240.html> rdfatest:subProp rdfatest:subProp .
  <http://localhost:8888/tests/html5/0240.html> rdfatest:baseProp rdfatest:subProp .
}
