PREFIX rdfatest: <http://rdfa.info/vocabs/rdfa-test#>
ASK WHERE {
  <http://localhost:8888/tests/html5/0242.html> rdfatest:eqProp rdfatest:eqProp .
  <http://localhost:8888/tests/html5/0242.html>  rdfatest:baseProp rdfatest:eqProp .
}
