PREFIX rdfatest: <http://rdfa.info/vocabs/rdfa-test#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
ASK WHERE {
  <http://localhost:8888/tests/html5/0243.html> <http://www.w3.org/ns/rdfa#usesVocabulary> <http://rdfa.info/vocabs/rdfa-test#> .
  <_:a> rdf:type rdfatest:SubClass .
  <_:a> rdf:type rdfatest:BaseClass .
}
