PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

ASK WHERE {
  <http://localhost:8888/tests/html5/0266.html> rdf:value "2012-03-18T00:00:00Z"^^xsd:dateTime  .
}
